### ISSUE TITLE
[BUG] I don´t know, but it doesn´t let me open or create any project 

### ISSUE THREAD

**Issue by Slenderino** [yeppiidev/MinecraftDatapackStudio#5]
**Describe the bug**
It does not let me open or create any project

**To Reproduce**
1. Go to 'File'
2. Click on 'Open project'
3. Select any project
4. See the error

**Expected behavior**
Open or create a project to me for work on

**Screenshots**
![image](https://github.com/yeppiidev/MinecraftDatapackStudio/assets/135389069/59fb85e2-1c00-4d14-b860-c0a9ce2d9da3)
![image](https://github.com/yeppiidev/MinecraftDatapackStudio/assets/135389069/abc441c6-98fa-460e-88a3-35ab2f65cdae)

**Desktop (please complete the following information):**
 - Windows Version: Windows 11 Pro 22H2
 - Datapack Studio Version: 1.0.0.12

**Comment by yeppiidev** [comment]
i probably didn't implement the open function properly. feel free to contribute to this project :)
